const WHOLE_DATA = 1;
const SCOOTER_VIN = 2;
const SCOOTER_ID = 3;
const SCOOTER_PLATE = 4;
const GOGORO_USER_ID = 5;
const GOGORO_USER_EMAIL = 6;
const ES_CONTRACT_ID = 7;
const NOT_CALCULATE_YET = 8;

export {
  WHOLE_DATA,
  SCOOTER_VIN,
  SCOOTER_ID,
  SCOOTER_PLATE,
  GOGORO_USER_EMAIL,
  GOGORO_USER_ID,
  ES_CONTRACT_ID,
  NOT_CALCULATE_YET,
};
