// Bill Needs to re-calculate
// Bill Success
const API_SUCCESS = 0;

// es-contract error
const UPDATE_ES_CONTRACT_FAILED = 998;
const GET_ES_CONTRACT_FAILED = 999;
const SEND_REQUEST_TO_BILLING_ENGINE_FAILED = 1000;
const GET_PROMOTION_FAILED = 1001;
const GET_ADDON_FAILED = 1002;
const GET_BILL_TO_USER_FAILED = 1003;
const GET_ES_CONTRACT_SCOOTER_FAILED = 1005;
const GET_USER_BY_EMAIL_FAILED = 1007;
const GET_CIPHER_FAILED = 1008;
const GET_BALANCE_FAILED = 1009;
const GET_PLAN_HISTORY_FAILED = 1010;
const NO_PLAN_TO_CALCULATE = 1011;
const NO_ES_CONTRACT = 1012;
const INVALID_BILLING_TIME_RANGE = 1015;
const GET_PLAN_FAILED = 1016;
const NO_BILL_TO_CALCULATE = 1019;

// es-bill error
const GET_ES_BILL_FAILED = 2000;
const GET_ES_BILL_SCOOTER_FAILED = 2001;
const GET_ES_BILL_SCOOTER_DETAIL_FAILED = 2002;
const ADD_BILL_FAILED = 2003;
const GET_LAST_BILL_FAILED = 2004;
const GET_INVOICE_DATA_FAILED = 2005;
const GET_RECALCULATE_BILL_FAILED = 2006;
const GET_WRITEOFF_DETAIL_FAILED = 2007;
const DUPLICATE_BILL = 302010006;

// scooter error
const GET_SCOOTER_SWAP_LOG_FAILED = 3000;
const GET_SCOOTER_EXEMPT_FAILED = 3001;
const UPDATE_SWAP_LOG_FAILED = 3002;
const GET_SCOOTER_FAILED = 3003;

export {
  UPDATE_ES_CONTRACT_FAILED,
  GET_ES_CONTRACT_FAILED,
  GET_PROMOTION_FAILED,
  GET_ADDON_FAILED,
  GET_BILL_TO_USER_FAILED,
  GET_SCOOTER_FAILED,
  GET_ES_CONTRACT_SCOOTER_FAILED,
  GET_USER_BY_EMAIL_FAILED,
  GET_CIPHER_FAILED,
  GET_BALANCE_FAILED,
  GET_PLAN_HISTORY_FAILED,
  NO_PLAN_TO_CALCULATE,
  INVALID_BILLING_TIME_RANGE,
  ADD_BILL_FAILED,
  GET_ES_BILL_FAILED,
  GET_ES_BILL_SCOOTER_FAILED,
  GET_SCOOTER_SWAP_LOG_FAILED,
  GET_SCOOTER_EXEMPT_FAILED,
  GET_ES_BILL_SCOOTER_DETAIL_FAILED,
  GET_RECALCULATE_BILL_FAILED,
  GET_PLAN_FAILED,
  GET_INVOICE_DATA_FAILED,
  NO_ES_CONTRACT,
  GET_LAST_BILL_FAILED,
  UPDATE_SWAP_LOG_FAILED,
  GET_WRITEOFF_DETAIL_FAILED,
  API_SUCCESS,
  SEND_REQUEST_TO_BILLING_ENGINE_FAILED,
  NO_BILL_TO_CALCULATE,
  DUPLICATE_BILL,
};
